export type ProjectCategory = "frontend" | "fullstack" | "backend" | "ai" | "all";

export interface Project {
  id: string;
  title: string;
  tagline: string;
  description: string;
  highlights: string[];
  tags: string[];
  category: ProjectCategory;
  liveUrl?: string;
  githubUrl?: string;
  caseStudyUrl?: string;
  role?: string;
  year?: string;
  featured: boolean;
  size?: "lg" | "md";
}

export const projects: Project[] = [
  {
    id: "syncapi",
    title: "SyncAPI",
    tagline: "Real-Time Collaborative API Workspace",
    description:
      "Postman, reimagined for teams — a real-time API workspace with live presence, shared collections, and auto-generated documentation that updates as you work.",
    highlights: [
      "Real-time co-editing with live presence indicators and team activity tracking via Socket.io",
      "Full request builder with multiple auth types, syntax-highlighted responses, and environment management",
      "Shared collections with drag-and-drop, complete request logging, and auto-generated shareable docs",
      "Monorepo architecture (Turborepo) with NestJS + Next.js services and Redis-backed presence cache",
    ],
    tags: ["Next.js 14", "TypeScript", "NestJS", "MongoDB", "Socket.io", "Redis", "Turborepo"],
    category: "fullstack",
    liveUrl: "https://syncapi-9fkn.onrender.com",
    githubUrl: "https://github.com/Asadur-Rehman/syncapi",
    caseStudyUrl: "/work/syncapi",
    year: "2026",
    featured: true,
    size: "lg",
  },
  {
    id: "flowcraft",
    title: "FlowCraft",
    tagline: "AI Workflow Automation Builder",
    description:
      "AI-powered workflow automation builder with a visual drag-and-drop interface for constructing and running automated pipelines with native AI nodes.",
    highlights: [
      "Drag-and-drop builder with trigger, action, and AI nodes (summarization, generation, classification)",
      "Queue-based async execution with retry and failure handling via BullMQ",
      "Real-time metrics, execution monitoring, and multi-tenant workspaces with RBAC",
      "External triggering via webhooks and REST APIs",
    ],
    tags: ["Next.js", "TypeScript", "React Flow", "Prisma", "BullMQ"],
    category: "ai",
    liveUrl: "https://flow-craft-pied.vercel.app/",
    githubUrl: "https://github.com/Asadur-Rehman/FlowCraft",
    caseStudyUrl: "/work/flowcraft",
    year: "2025",
    featured: true,
  },
  {
    id: "arcadia",
    title: "Arcadia",
    tagline: "NUST University Library System",
    description:
      "Digital library platform built exclusively for the NUST university community. Members can discover, borrow, and track thousands of books across multiple disciplines with real-time availability.",
    highlights: [
      "University ID verification for NUST-exclusive access control",
      "Single-click borrowing with real-time availability tracking and digital receipts",
      "Collection spanning CS, Engineering, Literature, and Social Sciences",
    ],
    tags: ["Next.js 15", "TypeScript", "PostgreSQL", "Drizzle ORM", "NextAuth v5", "Tailwind CSS", "Upstash Redis"],
    category: "fullstack",
    liveUrl: "https://arcadia-kqy3.vercel.app/",
    githubUrl: "https://github.com/Asadur-Rehman/arcadia",
    year: "2025",
    featured: true,
  },
  {
    id: "quicklaunch",
    title: "QuickLaunch",
    tagline: "AI Landing Page Generator",
    description:
      "AI-driven tool that generates conversion-optimized landing pages from a plain-language product description — from idea to a production-ready page in under 30 seconds.",
    highlights: [
      "Full landing page generated by Claude AI in under 30 seconds from a single prompt",
      "Visual section editor with inline editing and drag-to-reorder",
      "Multiple curated themes — color palettes and font combinations",
      "Clean, responsive HTML export with zero external dependencies",
    ],
    tags: ["Claude AI", "TypeScript", "Next.js", "HTML/CSS"],
    category: "ai",
    liveUrl: "https://quicklaunch-sigma.vercel.app/",
    githubUrl: "https://github.com/Asadur-Rehman/quicklaunch",
    year: "2025",
    featured: true,
  },
  {
    id: "kaloriekompass",
    title: "KalorieKompass",
    tagline: "Diet & Nutrition Platform",
    description:
      "Health-tech platform for personalized diet management and professional nutrition consultation with multi-role dashboards.",
    highlights: [
      "Calorie tracking with goal-based meal planning (loss/gain)",
      "Multi-role dashboards: users, dietitians, nutritionists, super admins",
      "Connect with certified nutritionists for personalized plans",
    ],
    tags: ["MongoDB", "Express.js", "React", "Node.js", "RBAC"],
    category: "fullstack",
    liveUrl: "https://kaloriekompass.com",
    featured: true,
  },
  {
    id: "talentscout",
    title: "TalentScout",
    tagline: "AI-Powered Recruitment Platform",
    description:
      "Cloud-based intelligent recruitment ecosystem that automates the entire hiring pipeline — from AI-generated job descriptions to live, evaluated AI interviews.",
    highlights: [
      "AI-generated JDs and intelligent resume↔job matching algorithms",
      "Real-time AI interviewer with webcam/mic, dynamic questioning, live evaluation",
      "Integrated coding assessment environment for technical roles",
      "Recruiter & organization dashboards with hiring funnel analytics",
    ],
    tags: ["React", "Node.js", "Express", "MongoDB", "OpenAI API", "WebRTC", "TailwindCSS"],
    category: "ai",
    githubUrl: "https://github.com/Asadur-Rehman/TalentScout",
    caseStudyUrl: "/work/talentscout",
    role: "Lead Developer & Architect — Final Year Project, NUST",
    year: "2025",
    featured: true,
  },
  {
    id: "task-tracker",
    title: "Task Tracker",
    tagline: "Enterprise Task Management System",
    description:
      "Advanced personal/team task management with Kanban columns, real-time sync, and a modern decoupled architecture.",
    highlights: [
      "Kanban-style boards, profile system, real-time updates",
      "Decoupled Next.js frontend talking to a NestJS backend",
      "Firebase Firestore + Admin SDK for auth and persistence",
    ],
    tags: ["Next.js 14", "TypeScript", "TailwindCSS", "TanStack Query", "NestJS", "Firebase"],
    category: "fullstack",
    githubUrl: "https://github.com/Asadur-Rehman/Task-Tracker",
    featured: true,
  },
  {
    id: "rag-chatbot",
    title: "RAG Chatbot",
    tagline: "AI Knowledge Assistant",
    description:
      "Retrieval-Augmented Generation chatbot for intelligent document Q&A — combining vector search with conversational LLM responses.",
    highlights: [
      "FAISS-powered similarity search with sentence-transformer embeddings",
      "Conversational AI built on Qwen1.5-1.8B-Chat",
      "FastAPI backend with an interactive Streamlit UI",
    ],
    tags: ["Python", "FastAPI", "Streamlit", "FAISS", "HuggingFace"],
    category: "ai",
    featured: true,
  },
  {
    id: "real-estate",
    title: "Real Estate Marketplace",
    tagline: "Full-Stack Property Platform",
    description:
      "Production-grade property listing and search platform with advanced filtering, image uploads and map integration.",
    highlights: [
      "Auth, property CRUD, multi-image uploads, advanced filters",
      "Responsive UI with map-based discovery",
    ],
    tags: ["MongoDB", "Express.js", "React", "Node.js"],
    category: "fullstack",
    githubUrl: "https://github.com/Asadur-Rehman/Real-Estate-App",
    featured: true,
  },
  {
    id: "blogging-platform",
    title: "Blogging Platform",
    tagline: "Full-Stack Content Management",
    description:
      "Feature-rich blogging platform with authentication, full CRUD, and rich text editing.",
    highlights: [
      "JWT-based auth with role-aware access",
      "Rich text editor and SEO-friendly post pages",
    ],
    tags: ["MongoDB", "Express.js", "React", "Node.js"],
    category: "fullstack",
    featured: true,
  },
];
